name: Build ShellCheck

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  deploy:
    name: Deploy binaries
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_EMAIL: ${{ secrets.DOCKER_EMAIL }}
          DOCKER_BASE: ${{ secrets.DOCKER_USERNAME }}/shellcheck
        run: |
          export TAGS="$(cat source/tags)"
          ( source ./.multi_arch_docker && set -eux && multi_arch_docker::main )
